application: still-toolbox-689
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /dist
  static_dir: dist
# - url: /api/.*
#   script: main.application

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
